-module(smelterl_plan_SUITE).

-include_lib("common_test/include/ct.hrl").

-export([all/0]).
-export([
    write_build_plan_env_with_loop_metadata/1,
    write_and_read_roundtrip_build_plan/1,
    read_rejects_unsupported_plan_version/1
]).

all() ->
    [
        write_build_plan_env_with_loop_metadata,
        write_and_read_roundtrip_build_plan,
        read_rejects_unsupported_plan_version
    ].

write_build_plan_env_with_loop_metadata(_Config) ->
    OutputDir = make_temp_dir("smelterl-plan-env"),
    OutputPath = filename:join(OutputDir, "build_plan.env"),
    BuildPlan = sample_plan_with_auxiliaries(),
    ok = smelterl_plan:write_env_file(OutputPath, BuildPlan),
    {ok, FileContents} = file:read_file(OutputPath),
    assert_contains(FileContents, <<"# Generated by smelterl - do not edit">>),
    assert_contains(FileContents, <<"ALLOY_PLAN_PRODUCT='demo'">>),
    assert_contains(FileContents, <<"ALLOY_PLAN_AUXILIARY_IDS=('aux_beta' 'aux_alpha')">>),
    assert_contains(
        FileContents,
        <<"ALLOY_PLAN_TARGET_IDS=('aux_beta' 'aux_alpha' 'main')">>
    ),
    assert_order(
        FileContents,
        <<"[\'aux_beta\']='auxiliary'">>,
        <<"[\'main\']='main'">>
    ),
    assert_order(
        FileContents,
        <<"[\'ALLOY_MOTHERLODE\']='${ALLOY_MOTHERLODE}'">>,
        <<"[\'FOO\']='bar baz'">>
    ),
    assert_equal(
        <<
            "product=demo\n"
            "main=main\n"
            "aux=aux_beta aux_alpha\n"
            "targets=aux_beta aux_alpha main\n"
            "kind=auxiliary\n"
            "root=aux_beta_root\n"
            "extra=${ALLOY_MOTHERLODE}\n"
        >>,
        source_env_and_print(OutputPath)
    ).

write_and_read_roundtrip_build_plan(_Config) ->
    OutputDir = make_temp_dir("smelterl-plan-roundtrip"),
    OutputPath = filename:join(OutputDir, "build_plan.term"),
    BuildPlan = sample_plan(),
    ok = smelterl_plan:write_file(OutputPath, BuildPlan),
    {ok, FileContents} = file:read_file(OutputPath),
    assert_contains(FileContents, <<"%% coding: utf-8">>),
    assert_contains(FileContents, <<"{build_plan,<<\"1.0\">>">>),
    {ok, ReadPlan} = smelterl_plan:read_file(OutputPath),
    assert_equal(BuildPlan, ReadPlan),
    {ok, MainTarget} = smelterl_plan:select_target(main, ReadPlan),
    assert_equal(main, maps:get(kind, MainTarget)).

read_rejects_unsupported_plan_version(_Config) ->
    OutputDir = make_temp_dir("smelterl-plan-unsupported"),
    OutputPath = filename:join(OutputDir, "build_plan.term"),
    ok = file:write_file(
        OutputPath,
        unicode:characters_to_binary(
            smelterl_file:format_term({build_plan, <<"9.9">>, []})
        )
    ),
    assert_equal(
        {error, {unsupported_plan_version, <<"9.9">>}},
        smelterl_plan:read_file(OutputPath)
    ).

sample_plan() ->
    sample_plan_without_auxiliaries().

sample_plan_without_auxiliaries() ->
    Target = #{
        id => main,
        kind => main,
        tree => #{root => demo, edges => #{demo => []}},
        topology => [demo],
        motherlode => #{nuggets => #{}, repositories => #{}},
        config => #{
            <<"ALLOY_CONFIG_TARGET_ARCH_TRIPLET">> =>
                {global, undefined, <<"arm-buildroot-linux-gnueabihf">>}
        },
        defconfig => #{regular => [], cumulative => []},
        capabilities => #{
            firmware_variants => [plain],
            variant_nuggets => #{plain => []},
            selectable_outputs => [],
            firmware_parameters => [],
            sdk_outputs_by_target => #{main => []}
        }
    },
    {ok, Plan} = smelterl_plan:new(
        demo,
        #{<<"ALLOY_MOTHERLODE">> => <<"${ALLOY_MOTHERLODE}">>},
        #{main => Target},
        [],
        #{
            product => demo,
            target_arch => <<"arm-buildroot-linux-gnueabihf">>,
            product_fields => #{},
            repositories => [],
            nugget_repo_map => #{demo => undefined},
            nuggets => [],
            auxiliary_products => [],
            capabilities => #{},
            sdk_outputs => [],
            external_components => [],
            smelterl_repository => smelterl
        }
    ),
    Plan.

sample_plan_with_auxiliaries() ->
    MainTarget = #{
        id => main,
        kind => main,
        tree => #{root => demo, edges => #{demo => [platform_core], platform_core => []}},
        topology => [platform_core, demo],
        motherlode => #{nuggets => #{}, repositories => #{}},
        config => #{
            <<"ALLOY_CONFIG_TARGET_ARCH_TRIPLET">> =>
                {global, undefined, <<"arm-buildroot-linux-gnueabihf">>}
        },
        defconfig => #{regular => [], cumulative => []},
        capabilities => sample_capabilities([aux_alpha, aux_beta])
    },
    AuxAlphaTarget = #{
        id => aux_alpha,
        kind => auxiliary,
        aux_root => aux_alpha_root,
        constraints => [],
        tree => #{
            root => aux_alpha_root,
            edges => #{aux_alpha_root => [platform_core], platform_core => []}
        },
        topology => [platform_core, aux_alpha_root],
        motherlode => #{nuggets => #{}, repositories => #{}},
        config => #{},
        defconfig => #{regular => [], cumulative => []},
        capabilities => sample_capabilities([aux_alpha, aux_beta])
    },
    AuxBetaTarget = #{
        id => aux_beta,
        kind => auxiliary,
        aux_root => aux_beta_root,
        constraints => [],
        tree => #{
            root => aux_beta_root,
            edges => #{aux_beta_root => [platform_core], platform_core => []}
        },
        topology => [platform_core, aux_beta_root],
        motherlode => #{nuggets => #{}, repositories => #{}},
        config => #{},
        defconfig => #{regular => [], cumulative => []},
        capabilities => sample_capabilities([aux_alpha, aux_beta])
    },
    {ok, Plan} = smelterl_plan:new(
        demo,
        #{
            <<"FOO">> => <<"bar baz">>,
            <<"ALLOY_MOTHERLODE">> => <<"${ALLOY_MOTHERLODE}">>
        },
        #{
            main => MainTarget,
            aux_alpha => AuxAlphaTarget,
            aux_beta => AuxBetaTarget
        },
        [aux_beta, aux_alpha],
        #{
            product => demo,
            target_arch => <<"arm-buildroot-linux-gnueabihf">>,
            product_fields => #{},
            repositories => [],
            nugget_repo_map => #{demo => undefined},
            nuggets => [],
            auxiliary_products => [],
            capabilities => #{},
            sdk_outputs => [],
            external_components => [],
            smelterl_repository => smelterl
        }
    ),
    Plan.

sample_capabilities(AuxiliaryIds) ->
    #{
        firmware_variants => [plain],
        variant_nuggets => #{plain => []},
        selectable_outputs => [],
        firmware_parameters => [],
        sdk_outputs_by_target =>
            maps:from_list([{TargetId, []} || TargetId <- [main | AuxiliaryIds]])
    }.

make_temp_dir(Prefix) ->
    make_temp_dir(Prefix, 0).

make_temp_dir(Prefix, Attempt) ->
    Suffix =
        integer_to_list(erlang:system_time(nanosecond)) ++ "-" ++
        integer_to_list(erlang:unique_integer([monotonic, positive])) ++ "-" ++
        integer_to_list(Attempt),
    Base = filename:join(os:getenv("TMPDIR", "/tmp"), Prefix ++ "-" ++ Suffix),
    case file:make_dir(Base) of
        ok ->
            Base;
        {error, eexist} ->
            make_temp_dir(Prefix, Attempt + 1)
    end.

assert_contains(Haystack, Needle) ->
    case binary:match(Haystack, Needle) of
        nomatch ->
            ct:fail("Expected ~tp to contain ~tp", [Haystack, Needle]);
        _ ->
            ok
    end.

assert_order(Haystack, FirstNeedle, SecondNeedle) ->
    case {
        binary:match(Haystack, FirstNeedle),
        binary:match(Haystack, SecondNeedle)
    } of
        {{FirstIndex, _}, {SecondIndex, _}} when FirstIndex < SecondIndex ->
            ok;
        {FirstMatch, SecondMatch} ->
            ct:fail(
                "Expected ~tp before ~tp in ~tp, got ~tp and ~tp",
                [FirstNeedle, SecondNeedle, Haystack, FirstMatch, SecondMatch]
            )
    end.

assert_equal(Expected, Actual) ->
    case Actual of
        Expected ->
            ok;
        _ ->
            ct:fail("Expected ~tp, got ~tp", [Expected, Actual])
    end.

source_env_and_print(Path) ->
    Port =
        open_port(
            {spawn_executable, os:find_executable("bash")},
            [
                binary,
                exit_status,
                stderr_to_stdout,
                use_stdio,
                {
                    args,
                    [
                        "-lc",
                        lists:flatten([
                            "source \"$1\"\n",
                            "printf 'product=%s\\n' \"$ALLOY_PLAN_PRODUCT\"\n",
                            "printf 'main=%s\\n' \"$ALLOY_PLAN_MAIN_TARGET\"\n",
                            "printf 'aux=%s\\n' \"${ALLOY_PLAN_AUXILIARY_IDS[*]}\"\n",
                            "printf 'targets=%s\\n' \"${ALLOY_PLAN_TARGET_IDS[*]}\"\n",
                            "printf 'kind=%s\\n' \"${ALLOY_PLAN_TARGET_KIND[aux_beta]}\"\n",
                            "printf 'root=%s\\n' \"${ALLOY_PLAN_TARGET_ROOT[aux_beta]}\"\n",
                            "printf 'extra=%s\\n' \"${ALLOY_PLAN_EXTRA_CONFIG[ALLOY_MOTHERLODE]}\"\n"
                        ]),
                        "--",
                        Path
                    ]
                }
            ]
        ),
    collect_port_output(Port, []).

collect_port_output(Port, Acc) ->
    receive
        {Port, {data, Data}} ->
            collect_port_output(Port, [Data | Acc]);
        {Port, {exit_status, 0}} ->
            iolist_to_binary(lists:reverse(Acc));
        {Port, {exit_status, Status}} ->
            ct:fail("bash sourcing failed with status ~B and output ~tp", [
                Status,
                iolist_to_binary(lists:reverse(Acc))
            ])
    end.
