-module(smelterl_gen_external_mk_SUITE).

-include_lib("common_test/include/ct.hrl").

-export([all/0]).
-export([
    generate_renders_root_and_package_makefiles_in_order/1,
    generate_reports_missing_packages_dir/1
]).

all() ->
    [
        generate_renders_root_and_package_makefiles_in_order,
        generate_reports_missing_packages_dir
    ].

generate_renders_root_and_package_makefiles_in_order(_Config) ->
    {Topology, Motherlode} = sample_target_inputs(),
    {ok, Content} = smelterl_gen_external_mk:generate(Topology, Motherlode),
    assert_equal(expected_external_mk(), iolist_to_binary(Content)).

generate_reports_missing_packages_dir(_Config) ->
    MissingRoot = make_temp_dir("smelterl-gen-external-mk-missing"),
    MissingRepo = filename:join(MissingRoot, "builtin"),
    ok = file:make_dir(MissingRepo),
    Motherlode = #{
        nuggets => #{
            broken_product => #{
                id => broken_product,
                repository => builtin,
                repo_path => path_binary(MissingRepo),
                nugget_relpath => <<"broken_product">>,
                buildroot => [{packages, <<"packages">>}]
            }
        },
        repositories => #{}
    },
    assert_equal(
        {error,
            {missing_packages_dir,
                broken_product,
                path_binary(filename:join(MissingRepo, "broken_product/packages"))}},
        smelterl_gen_external_mk:generate([broken_product], Motherlode)
    ).

sample_target_inputs() ->
    RootDir = make_temp_dir("smelterl-gen-external-mk"),
    RepoDir = filename:join(RootDir, "builtin"),
    ok = file:make_dir(RepoDir),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/external.mk"),
        "# platform root mk\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot/pkg_alpha")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/pkg_alpha/pkg-alpha.mk"),
        "# alpha mk\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot/pkg_zeta")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/pkg_zeta/pkg-zeta.mk"),
        "# zeta mk\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "product_core/packages/app_pkg")),
    ok = ensure_file(
        filename:join(RepoDir, "product_core/packages/app_pkg/app.mk"),
        "# app mk\n"
    ),
    Topology = [platform_core, product_core],
    Motherlode = #{
        nuggets => #{
            platform_core => #{
                id => platform_core,
                description => <<"Platform BSP">>,
                repository => builtin,
                repo_path => path_binary(RepoDir),
                nugget_relpath => <<"platform_core">>,
                buildroot => [{packages, <<"buildroot">>}]
            },
            product_core => #{
                id => product_core,
                description => <<"Product BSP">>,
                repository => builtin,
                repo_path => path_binary(RepoDir),
                nugget_relpath => <<"product_core">>,
                buildroot => [{packages, <<"packages">>}]
            }
        },
        repositories => #{}
    },
    {Topology, Motherlode}.

expected_external_mk() ->
    <<"# Generated by smelterl - do not edit\n"
      "\n"
      "## Nugget Packages ##\n"
      "\n"
      "# platform_core: Platform BSP\n"
      "include $(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/external.mk\n"
      "include $(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/pkg_alpha/pkg-alpha.mk\n"
      "include $(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/pkg_zeta/pkg-zeta.mk\n"
      "\n"
      "# product_core: Product BSP\n"
      "include $(ALLOY_MOTHERLODE)/builtin/product_core/packages/app_pkg/app.mk\n"
      "\n">>.

ensure_dir(Path) ->
    ok = filelib:ensure_dir(filename:join(Path, "dummy")),
    ok.

ensure_file(Path, Content) ->
    ok = filelib:ensure_dir(Path),
    ok = file:write_file(Path, Content).

make_temp_dir(Prefix) ->
    make_temp_dir(Prefix, 0).

make_temp_dir(Prefix, Attempt) ->
    Suffix =
        integer_to_list(erlang:system_time(nanosecond)) ++ "-" ++
        integer_to_list(erlang:unique_integer([monotonic, positive])) ++ "-" ++
        integer_to_list(Attempt),
    Base = filename:join(os:getenv("TMPDIR", "/tmp"), Prefix ++ "-" ++ Suffix),
    case file:make_dir(Base) of
        ok ->
            Base;
        {error, eexist} ->
            make_temp_dir(Prefix, Attempt + 1);
        {error, Reason} ->
            ct:fail("Failed to create temp dir ~ts: ~tp", [Base, Reason])
    end.

path_binary(Path) ->
    list_to_binary(filename:absname(Path)).

assert_equal(Expected, Actual) ->
    case Actual of
        Expected ->
            ok;
        _ ->
            ct:fail("Expected ~tp, got ~tp", [Expected, Actual])
    end.
