-module(smelterl_gen_config_in_SUITE).

-include_lib("common_test/include/ct.hrl").

-export([all/0]).
-export([
    generate_renders_extra_config_and_package_sources/1,
    generate_omits_comment_suffix_when_description_is_empty/1,
    generate_reports_missing_packages_dir/1
]).

all() ->
    [
        generate_renders_extra_config_and_package_sources,
        generate_omits_comment_suffix_when_description_is_empty,
        generate_reports_missing_packages_dir
    ].

generate_renders_extra_config_and_package_sources(_Config) ->
    {Topology, Motherlode} = sample_target_inputs(),
    {ok, Content} = smelterl_gen_config_in:generate(
        Topology,
        Motherlode,
        [<<"ALLOY_CACHE_DIR">>, <<"ALLOY_MOTHERLODE">>, <<"ALLOY_BUILD_DIR">>]
    ),
    assert_equal(expected_config_in(), iolist_to_binary(Content)).

generate_omits_comment_suffix_when_description_is_empty(_Config) ->
    RootDir = make_temp_dir("smelterl-gen-config-in-empty-description"),
    RepoDir = filename:join(RootDir, "builtin"),
    ok = file:make_dir(RepoDir),
    ok = ensure_dir(filename:join(RepoDir, "plain_product/packages")),
    ok = ensure_file(
        filename:join(RepoDir, "plain_product/packages/Config.in"),
        "# plain\n"
    ),
    Motherlode = #{
        nuggets => #{
            plain_product => #{
                id => plain_product,
                description => <<>>,
                repository => builtin,
                repo_path => path_binary(RepoDir),
                nugget_relpath => <<"plain_product">>,
                buildroot => [{packages, <<"packages">>}]
            }
        },
        repositories => #{}
    },
    {ok, Content} = smelterl_gen_config_in:generate(
        [plain_product],
        Motherlode,
        [<<"ALLOY_BUILD_DIR">>]
    ),
    assert_equal(
        <<"# Generated by smelterl - do not edit\n"
          "\n"
          "## Extra Buildroot Environment ##\n"
          "\n"
          "config ALLOY_MOTHERLODE\n"
          "\tstring\n"
          "\toption env=\"ALLOY_MOTHERLODE\"\n"
          "\n"
          "config ALLOY_BUILD_DIR\n"
          "\tstring\n"
          "\toption env=\"ALLOY_BUILD_DIR\"\n"
          "\n"
          "## Nugget Packages ##\n"
          "\n"
          "# plain_product\n"
          "source \"$(ALLOY_MOTHERLODE)/builtin/plain_product/packages/Config.in\"\n"
          "\n">>,
        iolist_to_binary(Content)
    ).

generate_reports_missing_packages_dir(_Config) ->
    MissingRoot = make_temp_dir("smelterl-gen-config-in-missing"),
    MissingRepo = filename:join(MissingRoot, "builtin"),
    ok = file:make_dir(MissingRepo),
    Motherlode = #{
        nuggets => #{
            broken_product => #{
                id => broken_product,
                repository => builtin,
                repo_path => path_binary(MissingRepo),
                nugget_relpath => <<"broken_product">>,
                buildroot => [{packages, <<"packages">>}]
            }
        },
        repositories => #{}
    },
    assert_equal(
        {error,
            {missing_packages_dir,
                broken_product,
                path_binary(filename:join(MissingRepo, "broken_product/packages"))}},
        smelterl_gen_config_in:generate(
            [broken_product],
            Motherlode,
            [<<"ALLOY_BUILD_DIR">>]
        )
    ).

sample_target_inputs() ->
    RootDir = make_temp_dir("smelterl-gen-config-in"),
    RepoDir = filename:join(RootDir, "builtin"),
    ok = file:make_dir(RepoDir),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/Config.in"),
        "# platform root\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot/pkg_alpha")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/pkg_alpha/Config.in"),
        "# alpha\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "platform_core/buildroot/pkg_zeta")),
    ok = ensure_file(
        filename:join(RepoDir, "platform_core/buildroot/pkg_zeta/Config.in"),
        "# zeta\n"
    ),
    ok = ensure_dir(filename:join(RepoDir, "product_core/packages/app_pkg")),
    ok = ensure_file(
        filename:join(RepoDir, "product_core/packages/app_pkg/Config.in"),
        "# app\n"
    ),
    Topology = [platform_core, product_core],
    Motherlode = #{
        nuggets => #{
            platform_core => #{
                id => platform_core,
                description => <<"Platform BSP">>,
                repository => builtin,
                repo_path => path_binary(RepoDir),
                nugget_relpath => <<"platform_core">>,
                buildroot => [{packages, <<"buildroot">>}]
            },
            product_core => #{
                id => product_core,
                description => <<"Product BSP">>,
                repository => builtin,
                repo_path => path_binary(RepoDir),
                nugget_relpath => <<"product_core">>,
                buildroot => [{packages, <<"packages">>}]
            }
        },
        repositories => #{}
    },
    {Topology, Motherlode}.

expected_config_in() ->
    <<"# Generated by smelterl - do not edit\n"
      "\n"
      "## Extra Buildroot Environment ##\n"
      "\n"
      "config ALLOY_MOTHERLODE\n"
      "\tstring\n"
      "\toption env=\"ALLOY_MOTHERLODE\"\n"
      "\n"
      "config ALLOY_BUILD_DIR\n"
      "\tstring\n"
      "\toption env=\"ALLOY_BUILD_DIR\"\n"
      "\n"
      "config ALLOY_CACHE_DIR\n"
      "\tstring\n"
      "\toption env=\"ALLOY_CACHE_DIR\"\n"
      "\n"
      "## Nugget Packages ##\n"
      "\n"
      "# platform_core: Platform BSP\n"
      "source \"$(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/Config.in\"\n"
      "source \"$(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/pkg_alpha/Config.in\"\n"
      "source \"$(ALLOY_MOTHERLODE)/builtin/platform_core/buildroot/pkg_zeta/Config.in\"\n"
      "\n"
      "# product_core: Product BSP\n"
      "source \"$(ALLOY_MOTHERLODE)/builtin/product_core/packages/app_pkg/Config.in\"\n"
      "\n">>.

ensure_dir(Path) ->
    ok = filelib:ensure_dir(filename:join(Path, "dummy")),
    ok.

ensure_file(Path, Content) ->
    ok = filelib:ensure_dir(Path),
    ok = file:write_file(Path, Content).

make_temp_dir(Prefix) ->
    make_temp_dir(Prefix, 0).

make_temp_dir(Prefix, Attempt) ->
    Suffix =
        integer_to_list(erlang:system_time(nanosecond)) ++ "-" ++
        integer_to_list(erlang:unique_integer([monotonic, positive])) ++ "-" ++
        integer_to_list(Attempt),
    Base = filename:join(os:getenv("TMPDIR", "/tmp"), Prefix ++ "-" ++ Suffix),
    case file:make_dir(Base) of
        ok ->
            Base;
        {error, eexist} ->
            make_temp_dir(Prefix, Attempt + 1);
        {error, Reason} ->
            ct:fail("Failed to create temp dir ~ts: ~tp", [Base, Reason])
    end.

path_binary(Path) ->
    list_to_binary(filename:absname(Path)).

assert_equal(Expected, Actual) ->
    case Actual of
        Expected ->
            ok;
        _ ->
            ct:fail("Expected ~tp, got ~tp", [Expected, Actual])
    end.
