%% Generated by smelterl Buildroot defconfig key spec generator.
%% Buildroot version: 2025.05
%% Buildroot describe: fcde5363aa
%% Buildroot commit: fcde5363aa35220a1f201159a05de652ec6f811f
%% Generated at: 2026-04-10T15:52:58Z
%% Explicit includes: none
%% Explicit overrides: none
%% Regenerate with:
%%   ./scripts/generate_defconfig_keys.escript --buildroot buildroot --output priv/defconfig-keys.spec

[
    {<<"BR2_ENABLE_LOCALE_WHITELIST">>, plain},
    {<<"BR2_GLOBAL_PATCH_DIR">>, path},
    {<<"BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_LINUX_KERNEL_CUSTOM_DTS_DIR">>, path},
    {<<"BR2_LINUX_KERNEL_PATCH">>, path},
    {<<"BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_PACKAGE_LINUX_BACKPORTS_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_PACKAGE_NCURSES_ADDITIONAL_TERMINFO">>, path},
    {<<"BR2_PACKAGE_NETSNMP_WITHOUT_MIB_MODULES">>, plain},
    {<<"BR2_PACKAGE_NETSNMP_WITH_MIB_MODULES">>, plain},
    {<<"BR2_PACKAGE_NGINX_ADD_MODULES">>, plain},
    {<<"BR2_PACKAGE_PANEL_MIPI_DBI_FIRMWARE_SOURCE">>, plain},
    {<<"BR2_PACKAGE_PERL_MODULES">>, plain},
    {<<"BR2_PACKAGE_QORIQ_MC_UTILS_DPC_INTREE">>, path},
    {<<"BR2_PACKAGE_QORIQ_MC_UTILS_DPL_CUSTOM_PATH">>, path},
    {<<"BR2_PACKAGE_QORIQ_MC_UTILS_DPL_INTREE">>, path},
    {<<"BR2_REFPOLICY_EXTRA_MODULES">>, plain},
    {<<"BR2_ROOTFS_DEVICE_TABLE">>, path},
    {<<"BR2_ROOTFS_OVERLAY">>, path},
    {<<"BR2_ROOTFS_POST_BUILD_SCRIPT">>, path},
    {<<"BR2_ROOTFS_POST_FAKEROOT_SCRIPT">>, path},
    {<<"BR2_ROOTFS_POST_IMAGE_SCRIPT">>, path},
    {<<"BR2_ROOTFS_PRE_BUILD_SCRIPT">>, path},
    {<<"BR2_ROOTFS_STATIC_DEVICE_TABLE">>, path},
    {<<"BR2_ROOTFS_USERS_TABLES">>, path},
    {<<"BR2_STRIP_EXCLUDE_FILES">>, plain},
    {<<"BR2_TARGET_ARM_TRUSTED_FIRMWARE_CUSTOM_DTS_PATH">>, path},
    {<<"BR2_TARGET_BAREBOX_AUX_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_TARGET_BAREBOX_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_TARGET_GRUB2_BUILTIN_MODULES">>, plain},
    {<<"BR2_TARGET_OPTEE_OS_CUSTOM_DTS_PATH">>, path},
    {<<"BR2_TARGET_ROOTFS_CPIO_DRACUT_CONF_FILES">>, path},
    {<<"BR2_TARGET_ROOTFS_OCI_ENV_VARS">>, plain},
    {<<"BR2_TARGET_SYSLINUX_C32">>, plain},
    {<<"BR2_TARGET_TI_K3_R5_LOADER_CUSTOM_DTS_PATH">>, path},
    {<<"BR2_TARGET_TZ_ZONELIST">>, plain},
    {<<"BR2_TARGET_UBOOT_CONFIG_FRAGMENT_FILES">>, path},
    {<<"BR2_TARGET_UBOOT_CUSTOM_DTS_PATH">>, path},
    {<<"BR2_TARGET_UBOOT_PATCH">>, path},
    {<<"BR2_TARGET_UBOOT_SPL_NAME">>, plain},
    {<<"BR2_UCLIBC_CONFIG_FRAGMENT_FILES">>, path}
].
